FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.version"="0.1.0"
LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IGhlbGxvLWFlcm9nZWFyLWFwYgpkZXNjcmlwdGlvbjogZGVwbG95\
cyBoZWxsby1hZXJvZ2VhciB3ZWIgYXBwbGljYXRpb24KYmluZGFibGU6IEZhbHNlCmFzeW5jOiBv\
cHRpb25hbAp0YWdzOgogIC0gbW9iaWxlLXNlcnZpY2UKbWV0YWRhdGE6CiAgZGlzcGxheU5hbWU6\
IEhlbGxvIEFlcm9nZWFyIChBUEIpCiAgc2VydmljZU5hbWU6IGhlbGxvLWFlcm9nZWFyLWFwYgog\
IGludGVncmF0aW9uczogaGVsbG8tYWVyb2dlYXItZGItYXBiCiAgcHJvdmlkZXJEaXNwbGF5TmFt\
ZTogIlJlZCBIYXQsIEluYy4iCnBsYW5zOgogIC0gbmFtZTogZGVmYXVsdAogICAgZGVzY3JpcHRp\
b246IEEgc2FtcGxlIEFQQiB3aGljaCBkZXBsb3lzIEhlbGxvIFdvcmxkCiAgICBmcmVlOiBUcnVl\
CiAgICBtZXRhZGF0YToge30KICAgIHBhcmFtZXRlcnM6IFtdCg=="

ADD playbooks /opt/apb/actions
ADD roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}

USER apb
